---
version: 0.2

phases:
  build:
    commands:
      - curl -qL -o jq https://stedolan.github.io/jq/download/linux64/jq && chmod +x ./jq
      - curl -O https://bootstrap.pypa.io/get-pip.py
      - python get-pip.py
      - pip install awscli
      - aws --version
      - curl -qL -o aws_credentials.json http://169.254.170.2/$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI > aws_credentials.json
      - aws configure set region $AWS_REGION
      - aws configure set aws_access_key_id `./jq -r '.AccessKeyId' aws_credentials.json`
      - aws configure set aws_secret_access_key `./jq -r '.SecretAccessKey' aws_credentials.json`
      - aws configure set aws_session_token `./jq -r '.Token' aws_credentials.json`
      - aws s3 sync aws s3://solodev-aws-ha/aws --delete
      - DATE=$(date +%d%m"-"%H%M)
      - echo "Delete Old Stacks"
      - aws cloudformation describe-stacks --query "Stacks[].[StackName]"
      - NAMES=$(aws cloudformation describe-stacks --query "Stacks[].[StackName]")
      - for name in $NAMES[0]
        do
          echo "Who are you?"
          echo "I am $name"
        done
      - echo "Create Stacks:"
      # - echo "Create Solodev Lite"
      # - echo $(aws s3 cp s3://build-secure/params/solodev-lite-single.json - ) > solodev-lite-single.json
      # - aws cloudformation create-stack --stack-name lite-${DATE} --disable-rollback --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM
      #   --parameters file:///${CODEBUILD_SRC_DIR}/solodev-lite-single.json
      #   --template-url https://s3.amazonaws.com/solodev-aws-ha/aws/solodev-lite-single.yaml
      # - echo "Create Solodev Pro Single"
      # - echo $(aws s3 cp s3://build-secure/params/solodev-pro-single.json - ) > solodev-pro-single.json
      # - aws cloudformation create-stack --stack-name pro-${DATE} --disable-rollback --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM
      #   --parameters file:///${CODEBUILD_SRC_DIR}/solodev-pro-single.json
      #   --template-url https://s3.amazonaws.com/solodev-aws-ha/aws/solodev-pro-single.yaml
      # - echo "Create Solodev Opsworks"
      # - echo $(aws s3 cp s3://build-secure/params/solodev-enterprise-opsworks.json - ) > solodev-enterprise-opsworks.json
      # - aws cloudformation create-stack --stack-name opsworks-${DATE} --disable-rollback --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM
      #   --parameters file:///${CODEBUILD_SRC_DIR}/solodev-enterprise-opsworks.json
      #   --template-url https://s3.amazonaws.com/solodev-aws-ha/aws/solodev-enterprise-opsworks.yaml
      - echo "Create Solodev ECS"
      - echo $(aws s3 cp s3://build-secure/params/solodev-enterprise-ecs.json - ) > solodev-enterprise-ecs.json
      - aws cloudformation create-stack --stack-name ecs-${DATE} --disable-rollback --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM
        --parameters file:///${CODEBUILD_SRC_DIR}/solodev-enterprise-ecs.json
        --template-url https://s3.amazonaws.com/solodev-aws-ha/aws/solodev-enterprise-ecs.yaml
      - echo "Cleanup" | rm -f *json
  post_build:
    commands:
      - echo "S3 synced on `date`"