---
AWSTemplateFormatVersion: '2010-09-09'

Description: >

    Solodev CMS Enterprise for Docker ECS on AWS

Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "Network Setup"
        Parameters: 
          - VPCID
          - Subnets
          - InstanceType
          - KeyName
      - 
        Label: 
          default: "CMS Settings"
        Parameters: 
            - AdminUser
            - AdminPassword
            - DatabaseName
            - DatabaseUsername
            - DatabasePassword
      - 
        Label: 
          default: "Optional: SSL Configuration"
        Parameters: 
          - FQDN
          - CertificateArn
      - 
        Label: 
          default: "Optional: Advanced"
        Parameters: 
          - RestoreBucketName
          - AMI
          - DeletionPolicy
      - 
        Label: 
          default: "Optional: Private Access (Required if not purchased through AWS)"
        Parameters: 
          - SolodevContainer
          - ApacheContainer
          - DockerUsername
          - DockerPassword
          - DockerEmail

Mappings:
  ECS:
    us-east-1:
      AMI: "ami-0b9a214f40c38d5eb"
    us-west-1:
      AMI: ""
    us-west-2:
      AMI: ""
    eu-west-1:
      AMI: ""
    sa-east-1:
      AMI: ""
    ap-southeast-1:
      AMI: ""
    ap-southeast-2:
      AMI: ""
    ap-northeast-1:
      AMI: ""

Parameters:

    VPCID: 
        Type: AWS::EC2::VPC::Id
        Description: Choose which VPC the Application should be deployed to
        AllowedPattern: .+
        ConstraintDescription: Please choose VPC

    Subnets:
        Description: Choose at least two public subnets for this application
        Type: List<AWS::EC2::Subnet::Id>
        AllowedPattern: .+
        ConstraintDescription: Please choose Subnets

    KeyName:
        Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
        Type: 'AWS::EC2::KeyPair::KeyName'
        AllowedPattern: .+
        ConstraintDescription: Please choose EC2 KeyPair

    InstanceType:
        Type: String
        Default: m3.medium
        AllowedValues: [t2.micro, t2.small, t2.medium, t2.large, m3.medium, m3.large,
        m3.xlarge, m3.2xlarge, m4.large, m4.xlarge, m4.2xlarge, m4.4xlarge, m4.10xlarge,
        c4.large, c4.xlarge, c4.2xlarge, c4.4xlarge, c4.8xlarge, c3.large, c3.xlarge,
        c3.2xlarge, c3.4xlarge, c3.8xlarge, r3.large, r3.xlarge, r3.2xlarge, r3.4xlarge,
        r3.8xlarge, i2.xlarge, i2.2xlarge, i2.4xlarge, i2.8xlarge]
        ConstraintDescription: Please choose a valid instance type.

    AMI:
        Description: 'Experimental: Build AMI (Please leave this blank unless told otherwise)'
        Default: ''
        Type: String

    DeletionPolicy:
        Default: 'Delete'
        Type: String
        Description: 'Experimental: Deletion Policy (Retain, Delete, Snapshot)'

    FQDN:
        Type: String
        Description: URL for app. FQDN must be pointed to CNAME of ALB.

    CertificateArn:
        Type: String
        Description: CertificateArn for SSL cert that matches the FQDN above. Please visit the AWS Certificate Manager.

    AdminUser:
        Description: The solodev admin username
        Type: String
        Default: 'solodev'
        AllowedPattern: .+
        ConstraintDescription: Please set admin username

    AdminPassword:
        NoEcho: true
        Description: The solodev admin password
        Type: String
        MinLength: 1
        MaxLength: 41
        AllowedPattern: .+
        ConstraintDescription: Please set admin password

    DatabaseName:
        Type: String
        Description: The database name
        Default: "solodev"

    DatabaseUsername:
        Description: Database root user
        Type: String
        Default: 'root'

    DatabasePassword:
        NoEcho: true
        Description: The database root password
        Type: String
        MinLength: 1
        MaxLength: 41
        AllowedPattern: .+
        ConstraintDescription: Please set database root password

    RestoreBucketName:
        Description: Name of S3 bucket containing files for restore
        Type: String
        Default: ""

    SolodevContainer:
        Description: Solodev container image
        Default: 'solodev/cms:latest'
        Type: String

    ApacheContainer:
        Description: Apache container image
        Default: 'solodev/cms-apache:latest'
        Type: String

    DockerUsername:
        Description: Docker username
        Type: String

    DockerPassword:
        NoEcho: true
        Description: Docker password
        Type: String

    DockerEmail:
        Description: Docker email address
        Type: String

Conditions:
    UseDefaultAMI: !Equals [ !Ref AMI, "" ]

Resources:

    ALB:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3.amazonaws.com/solodev-aws-ha/aws/infrastructure/alb.yaml
            Parameters:
                EnvironmentName: !Ref AWS::StackName
                VPC: !Ref VPCID
                Subnets: !Join [",", [!Select [0, !Ref Subnets], !Select [1, !Ref Subnets]]]

    EFS:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3.amazonaws.com/solodev-aws-ha/aws/infrastructure/efs.yaml
            Parameters:
                EnvironmentName: !Ref AWS::StackName
                VPC: !Ref VPCID
                Subnets: !Join [",", [!Select [0, !Ref Subnets], !Select [1, !Ref Subnets]]]

    ECS:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3.amazonaws.com/solodev-aws-ha/aws/infrastructure/ecs.yaml
            Parameters:
                EnvironmentName: !Ref AWS::StackName
                AWSStackId: !Ref AWS::StackId
                InstanceType: !Ref InstanceType
                AMI: !If [UseDefaultAMI, !FindInMap ["ECS", !Ref "AWS::Region", AMI], !Ref AMI]
                ClusterSize: 2
                VPC: !Ref VPCID
                EFS: !GetAtt EFS.Outputs.EFS
                DockerUsername: !Ref DockerUsername
                DockerPassword: !Ref DockerPassword
                DockerEmail: !Ref DockerEmail
                LoadBalancerSecurityGroup: !GetAtt ALB.Outputs.LoadBalancerSecurityGroup
                Subnets: !Join [",", [!Select [0, !Ref Subnets], !Select [1, !Ref Subnets]]]
                KeyName: !Ref KeyName
                # DeploymentType: "dev"

    RDS:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3.amazonaws.com/solodev-aws-ha/aws/infrastructure/rds.yaml
            Parameters:
                EnvironmentName: !Ref AWS::StackName
                DatabaseName: !Ref DatabaseName
                VPC: !Ref VPCID
                LoadBalancerSecurityGroup: !GetAtt ECS.Outputs.ECSHostSecurityGroup
                Subnets: !Join [",", [!Select [0, !Ref Subnets], !Select [1, !Ref Subnets]]]
                DatabasePassword: !Ref DatabasePassword
                DeletionPolicy: !Ref DeletionPolicy

    # PROXY:
    #     Type: AWS::CloudFormation::Stack
    #     Properties:
    #         TemplateURL: https://s3.amazonaws.com/solodev-aws-ha/aws/services/nginx-proxy-ecs.yaml
    #         Parameters:
    #             EnvironmentName: !Ref AWS::StackName
    #             VPC: !Ref VPCID
    #             Cluster: !GetAtt ECS.Outputs.Cluster
    #             LoadBalancer: !GetAtt ALB.Outputs.LoadBalancer
    #             LoadBalancerSecurityGroup: !GetAtt ALB.Outputs.LoadBalancerSecurityGroup
    #             DesiredCount: 2
    #             ServiceRole: !GetAtt ALB.Outputs.ServiceRole 
    #             Path: /

    SOLODEV:
        Type: AWS::CloudFormation::Stack
        DependsOn: RDS
        Properties:
            TemplateURL: https://s3.amazonaws.com/solodev-aws-ha/aws/services/ecs-solodev.yaml
            Parameters:
                EnvironmentName: !Ref AWS::StackName
                VPC: !Ref VPCID
                Cluster: !GetAtt ECS.Outputs.Cluster
                ClusterArn: !GetAtt ECS.Outputs.ClusterArn
                LoadBalancer: !GetAtt ALB.Outputs.LoadBalancer
                LoadBalancerSecurityGroup: !GetAtt ALB.Outputs.LoadBalancerSecurityGroup
                Subnets: !Join [",", [!Select [0, !Ref Subnets], !Select [1, !Ref Subnets]]]
                AdminUsername: !Ref AdminUser
                AdminPassword: !Ref AdminPassword
                DatabaseHost: !GetAtt RDS.Outputs.DatabaseHost
                DatabaseName: !Ref DatabaseName
                DatabaseUsername: !Ref DatabaseUsername
                DatabasePassword: !Ref DatabasePassword
                FQDN: !Ref FQDN
                CertificateArn: !Ref CertificateArn
                SolodevContainer: !Ref SolodevContainer
                ApacheContainer: !Ref ApacheContainer
                MongoContainer: 'techcto/mongo:latest'
                RestoreBucketName: !Ref RestoreBucketName
                DesiredCount: 2
                ServiceRole: !GetAtt ALB.Outputs.ServiceRole 
                Path: / 
                DeletionPolicy: !Ref DeletionPolicy

Outputs:

    URL: 
        Description: The URL endpoint for the website service
        Value: !Join ["", [ "http://", !GetAtt ALB.Outputs.LoadBalancerUrl, "/" ]]